version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - run:
          name: Run npm install
          command: npm install
      - run:
          name: Run unit tests
          command: npm run test